name: Merge into Main
on:
  push:
    branches:
      - main
jobs:
  deploy-infra:
    defaults:
      run:
        working-directory: ./infra
    permissions:
      pull-requests: write
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'us-west-2'
          role-to-assume: "arn:aws:iam::975050125701:role/victor-hobby-github"
          role-skip-session-tagging: true
      - name: OpenTofu - Setup Tofu
        uses: opentofu/setup-opentofu@v1.0.3
        with:
            tofu_version: 1.7.2
      - name: Initialize Tofu
        run: tofu init -backend-config="key=${{ github.event.repository.name }}/prod.tfstate"
      - name: OpenTofu fmt
        id: fmt
        run: tofu fmt -check
      - name: OpenTofu Validate
        id: validate
        working-directory: ./infra
        run: tofu validate -no-color
      - name: OpenTofu Plan
        id: plan
        run: tofu plan -no-color -var="stage_prefix=prod"
      - name: OpenTofu Apply
        id: apply
        run: tofu apply -no-color -var="stage_prefix=prod" -auto-approve
  setup-node:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 🏗 Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          cache-dependency-path: ./frontend/package-lock.json
          node-version: 20.x
          cache: npm
      - name: 📦 Install dependencies
        run: npm install
      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_ACCESS_TOKEN }}
  deploy-app:
    needs: setup-node
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Create update
        run: eas update --auto --non-interactive
  deploy-web:
    needs: setup-node
    permissions:
      contents: write
      id-token: write
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
      - name: Generate Artifacts
        id: generate-artifacts
        run: npx expo export -p web
      - name: Upload Artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./frontend/dist
          name: github-pages
          overwrite: true
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}


